[server]
# 服务端口
port = 8070
# 读超时，单位毫秒
readTimeout = 5000
# 写超时，单位毫秒
writeTimeout = 5000

[etcd]
# etcd集群地址
endPoints = ["127.0.0.1:2379"]
# 超时时间
dialTimeout = 50000

[mongodb]
# mongodb地址
host= "127.0.0.1:27017"
# 连接超时时间(毫秒)
timeOut = "5000"
